In [ ]:
#TODAY TOPICS
# LAMBDA
# MAP
# FILTER

In [ ]:
#LAMBDA -->1. A lambda function is a small ananymous function. Anonymous means the function does not have a name .
          #2. Lambda function are useful when a function is needed only once and does not need reused elsewhere

   # Syntax : lambda arguments : expression --> a = lambda x: x ** 2
   #  a= function name
   #  lambda = function keyword
   #  x= argument
   #  ** = expression

   #Interview Definition

#Lambda function is an anonymous, single-expression function defined using the lambda keyword.

square = lambda x:x*x
print(square(5))

tax = lambda x:x*0.03
print(tax(400000))

sum = lambda a,b : a+b
print(sum(16,11))

max = lambda a,b: a if a>b else b
print(max(16,11))



25
12000.0
27
16


In [ ]:
#MAP --> the MAP() function applies the same operation to every item in a collection
# Syntax --> map(function, iterable)

numbers= [1,2,3,4,5]
result= map(lambda x:x *2,numbers)
print(list(result))

[2, 4, 6, 8, 10]


In [ ]:
# FILTER --> The filter() function selects only the items that satisfy a condition
# Syntax --> filter(function, iterable)

numbers = [1,2,3,4,5,6]
even_numbers = filter(lambda x: x%2==0,numbers)
print(list(even_numbers))

[2, 4, 6]


In [ ]:
#REDUCE FUNCTION -->Reduce combines all values into a singel value.
                    #It repeatedly performs an action until only one result remains
#IMPORT --> from functools import reduce
#SYNTAX --> reduce(function , iterable)
from functools import reduce
numbers = [1,2,3,4]
result = reduce(lambda x,y:x+y,numbers)
print(result)

10


In [ ]:
#ZIP FUNCTION -->The zip() function combines two or more iterables (lists, tuples, etc.) element by element into pairs (or tuples).
#Syntax --> zip(iterable1,iterable2,...)
names = ["Mukesh", "Rahul", "Kiran"]
marks = [85, 90, 88]

result = list(zip(names, marks))

print(result)

[('Mukesh', 85), ('Rahul', 90), ('Kiran', 88)]


In [ ]:
#ENUMERATE FUNCTION --> The enumerate() function automatically adds an index number.

fruits = ["apple", "banana", "mango"]
for index, fruit in enumerate(fruits, start=1):
    print(index, fruit)

1 apple
2 banana
3 mango


In [ ]:
#SORTED FUNCTION --> Sort() function sorts the data in ascending or decending order

numbers = [1,3,4,2,7,0]
numbers.sort()
print(numbers)

[0, 1, 2, 3, 4, 7]


In [ ]:
#ANY FUNCTION --> Prints TRUE if any condition is true
a=30
b=45
numbers = [a>b , a<b]
print(any(numbers))

True


In [ ]:
#ALL FUNCTION -->The all() function returns True only if all elements in an iterable are True

a=45
b=45
numbers = [a>=b,a<=b,a==b]
print(all(numbers))

True


# NUMPY
  

NumPy is a fundmental package for numerical computing in python. It provides support of multi dimensional array and matrices . along with mathemetical functions

In [24]:
#NUMPY -- >NumPy is a fundmental package for numerical computing in python. It provides support for dimensional arrays
!pip install NumPy
import numpy as np
import sys
list_1000000=list(range(1000000))
array_1000000=np.arange(1000000)
print(f"size of list: {sys.getsizeof(list_1000000)} bytes")
print(f"size of array: {array_1000000.nbytes} bytes")
import time

#sum the list
start_time= time.time()
sum_list=np.sum(list_1000000)
end_time=time.time()
list_sum_time = (end_time-start_time) *1000

#sum the array
start_time = time.time()
sum_array = np.sum(array_1000000)
end_time = time.time()
array_sum_time = (end_time-start_time)*1000

print(f"sum of list: {list_sum_time:.2f} milliseconds")
print(f"sum of array: {array_sum_time:.2f} milliseconds")

size of list: 8000056 bytes
size of array: 8000000 bytes
sum of list: 69.48 milliseconds
sum of array: 1.25 milliseconds


# CREATE AN NUMPY 1D ARRAY

Buildin Methods:
  1. zeros() --> Return all 0's in array
  2. ones() --> Return all 1's in array
  3. Random() --> Create an random float values between zero and one
  4. arange() --> Creation of array with a fixed step size between values
  5. linspace() --> Generates evenly spaced numbers
  



In [23]:
print(np.array([1,4,2]))

print(np.zeros(5))

print(np.ones(4))

print(np.random.random(5))

print(np.arange(0,25,5))

print(np.arange(1,10))

print(np.linspace(2,10,5))

[1 4 2]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[0.67159769 0.40699236 0.70842728 0.54946313 0.79502897]
[ 0  5 10 15 20]
[1 2 3 4 5 6 7 8 9]
[ 2.  4.  6.  8. 10.]


# CREATING 2D ARRAY
  A 2D(two dimensional)array is an array that contains data in rows and columns like table & matrix.

**Syntax:**
      array_name = np.function_name ([values , values])
      eg : arr=np.array([[1,2,3],[4,5,6]])

    Methods :
      1. zeros() -->
      2. ones() -->
      3. arange() --> It create an 2D array using arange and reshape it using  reshape().
      4. Reshape() --> It is used to change the shape of an array without changing data.

In [ ]:
import numpy as np
print(np.array([[1,2,3],[4,5,6]]))

print(np.zeros((2,2)))

print(np.ones((3,2)))

print(np.arange(1,7).reshape(3,2))

# 3D ARRAY
    A 3D array is an array that contains multiple 2D array

In [15]:
import numpy as np
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

print(np.zeros((2,2,3)))

print(np.ones((3,2,2)))

print(np.arange(1,17).reshape(2,4,2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


# ATTRIBUTES
  1. ndim() --> Returns number of dimension of the array
  2. size() --> Returns number of elements in the array
  3. shape() --> Returns shape of the array in each dimensions
  4. dtype() --> Returns data type of elements in the array


In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.dtype)

p = np.array([1,2,3])
print(p.ndim)
print(p.shape)

2
6
(2, 3)
int64
1
(3,)


# INDEXING
    It allow us to access specific element in an array using position

    2D ARRAY --> Elements are accessed using two indices
    Syntax -->
        arr[row_position, column_position]

In [13]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[-2,-2])
print(arr[0,2])

[[1 2 3]
 [4 5 6]]
2
3


# SLICING
    Slicing is used to extract a portion of an array.

  Syntax -->
        arr[start : stop : step]

  2D array -->
    Syntax -->
       arr[start_row : end_row : step , start_col : end_col : step ]

In [ ]:
import numpy as np

arr = np.arange(10)

print(arr)

print(arr[1:6])

print(arr[::-1])

print(arr[1: :2])

print(arr[1:6:2])

print(arr[:8:3])

a = np.arange(8).reshape(4,2)

print(a)

print(a[0:3,0:1])

print(a[0])

print(a[0,:])


In [6]:
import numpy as np
arr= np.arange(10)
print(arr[arr%2==0])

print(arr[(arr>2) & (arr<9)])

[0 2 4 6 8]
[3 4 5 6 7 8]


# ARITHMETIC OPERATIONS

    1. Addition (+)
    2. Subtraction (-)
    3. Multiplication (*)
    4. Division (/)
    5. modulus (%)
    6. floor division (//)
    7. exponentiation (**)
    
Vectorization --> Perform operations on entire arrays at once , without explicit the loop

In [ ]:
import numpy as np

a= np.array([1,2,4])
b= np.array([4,5,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%2)
print(a//b)

# BROADCASTING
  --> It allows array to different shapes to perform arithmetic opeations without explicitly reshaping them.
  --> Broadcasting automatically expands the smaller array to match the shape of the larger array.

In [7]:
import numpy as np
a = np.array([1,2,5,8])
print(a+5)

b= np.array([[1,5,10,15],[2,4,6,8]])
print(b+a)

c= np.array([[1],[2]])

print(b+c)

[ 6  7 10 13]
[[ 2  7 15 23]
 [ 3  6 11 16]]
[[ 2  6 11 16]
 [ 4  6  8 10]]


# DESCRIPTIVE METHODS
    --> Descriptive methods are used to summerize and analyze data, Providing key statistics like mean, median, standard deviation etc..
    -->They are essential for data analysis, making it easier to spot trends and patterns in a dataset.

  1. sum() --> computes the sum of array elements --> np.sum(arr,axis=0/1/none)
  2. mean() --> Computes the average value of an array.
  3. standard deviation() --> Standard Deviation measures how far the data values are spread from the mean.
      --> Low standard deviation → Data points are close to the mean.
      --> High standard deviation → Data points are spread far from the mean.
  4. Variance() --> Variance measures how far data values are spread from the mean (average).
      --> It tells us the average of the squared differences from the mean.

          --> Small variance → Data is close to the mean.
          --> Large variance → Data is widely spread.
  5. Minimum() --> Returns minimum value of the array
  6. Maximum() --> Returns maximum value of the array
  7. argmin() --> Return the index of the minimum value of the array
  8. argmax() --> Returns teh index of the maximun value of the array
  


In [ ]:
import numpy as np
#SUM
a=np.arange(1,5)
# a=np.array([1,2,3,4,5])
print(np.sum(a))

b=np.arange(1,9).reshape(2,4)
print(b)
print(np.sum(b))
print(np.sum(b,axis=0))
print(np.sum(b,axis=1))

#MEAN
print(np.mean(a))
print(np.mean(b))
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))

#STANDARD DEVIATION
print(np.std(a))

#VARIANCE
print(np.var(a))
print(np.var(b))
print(np.var(b,axis=0))
print(np.var(b,axis=1))

#MINIMUM
print(np.min(a))
print(np.min(b))
print(np.min(b,axis=0))
print(np.min(b,axis=1))

#MAXIMUM
print(np.max(a))
print(np.max(b))
print(np.max(b,axis=0))
print(np.max(b,axis=1))

#ARGMIN
c=np.array([8,4,52,1,0])
print(np.argmin(c))
print(np.argmin(b))
print(np.argmin(b,axis=0))
print(np.argmin(b,axis=1))

#ARGMAX
print(np.argmax(c))
print(np.argmax(b))
print(np.argmax(b,axis=0))
print(np.argmax(b,axis=1))

10
[[1 2 3 4]
 [5 6 7 8]]
36
[ 6  8 10 12]
[10 26]
2.5
4.5
[3. 4. 5. 6.]
[2.5 6.5]
1.118033988749895
1.25
5.25
[4. 4. 4. 4.]
[1.25 1.25]
1
1
[1 2 3 4]
[1 5]
4
8
[5 6 7 8]
[4 8]
4
0
[0 0 0 0]
[0 0]
2
7
[1 1 1 1]
[3 3]
