<a href="https://colab.research.google.com/github/mukhi19113/Adyapan/blob/main/Numpy_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. Array of Consecutive Numbers:
Create a one-dimensional NumPy array containing the first ten whole numbers. Use this array for subsequent exercises to practice basic array operations.

In [3]:
a= np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Squares of Numbers:
Given a one-dimensional array of integers, write a NumPy code that calculates the square of each element. This exercise helps understand element-wise operations in arrays.

In [6]:
square_numbers = lambda a : a**2
square_numbers(a)


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

3. Dimension Transformation:
Take a sequence of numbers from 0 to 9 and reshape it into a two-dimensional array with 2 rows and 5 columns. Explore how reshaping changes the structure of data, which is crucial in data preprocessing.

In [8]:
reshape_array = a.reshape(2,5)
reshape_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Slice of Life:
Extract a slice from the third to the fifth elements inclusive from a given one-dimensional array. Discuss how slicing can be used to subset data, a common task in data analysis.

In [9]:
slice_array = a[2:5]
slice_array

array([2, 3, 4])

5. Conditional Mastery:
Write a NumPy program to select all elements from an array that are greater than 5. This task illustrates how to use conditional statements for data filtering.

In [16]:
conditional_array= np.where(a>5)[0].tolist()
conditional_array

[6, 7, 8, 9]

6. Statistical Analysis:
Calculate the mean, median, and standard deviation of an array's elements. This introduces the basic statistical functions in NumPy, essential for any data analysis.

In [22]:
#Mean
print(mean = np.mean(a))
#Median
print(median = np.median(a))
#Standard Deviation
print(sd = np.std(a))

7. Matrix Product:
Perform a matrix multiplication between two 2x2 matrices. Explore how matrix operations are performed in NumPy, which is fundamental for algorithms involving linear transformations and neural networks.

In [31]:
b= np.array([[2,4],
             [1,3]])
c= np.array([[6,8],
             [5,7]])
print(np.matmul(b,c))

[[32 44]
 [21 29]]


8. Odd One Out:
Use boolean indexing to replace all odd numbers in an array with -1. This problem helps understand boolean masking, a powerful feature for modifying arrays based on conditions.

In [36]:
a[a%2==1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


9. Random Number Generation:
Create a 3x3 matrix with random numbers drawn from a normal distribution. Investigate the properties of random distributions and their applications.

In [53]:
random_array = np.random.random(9).reshape(3,3)
random_array

array([[0.58604172, 0.31333026, 0.5357766 ],
       [0.95331397, 0.3829567 , 0.08337635],
       [0.58207693, 0.71250615, 0.80029083]])

10. Join the Arrays:
Learn how to concatenate two 1D arrays both vertically and horizontally. This operation is critical in combining data from different sources.

In [57]:
a=np.arange(10)
b=np.arange(10,20)
concat_array = np.concatenate((a,b))
concat_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
a=np.arange(6).reshape(2,3)
b=np.arange(10,16).reshape(2,3)
concat_array1 = np.concatenate((a,b),axis= 1) # horizontal
concat_array2 = np.concatenate((a,b),axis = 0) # Vertical
print(concat_array1)
print(concat_array2)

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]


11. Common Ground:
Find the intersection of two one-dimensional arrays. This exercise is useful in data comparison tasks, such as finding common elements in data sets.

In [63]:
arr1 = np.arange(1,7)
arr2 = np.array([1,8,3,9,2])
common_elements = np.intersect1d(arr1,arr2)
common_elements

array([1, 2, 3])

In [62]:
arr = np.array([[1,2,5],[3,4,2]])
arr2 = np.array([[2,5,3],[7,9,3]])
common_elements = np.intersect1d(arr,arr2)
common_elements

array([2, 3, 5])

12. Data Ingestion:
Load a dataset from a CSV file into a NumPy array and extract just the first column. This demonstrates how NumPy can be used for initial data handling before in-depth analysis.

In [72]:
arr = np.loadtxt('/content/data.csv',delimiter=',',skiprows=1)
arr1 =arr[:,0]
print(arr1)

[1. 4. 7.]


13. Complex Numbers Handling:
Create and sort a one-dimensional array of complex numbers based on their real part. This will help understand how NumPy handles complex number data types.

In [75]:
arr1 = np.array([3+4j,2+3j,5+5j])
arr2 = np.sort(arr1)
arr2

array([2.+3.j, 3.+4.j, 5.+5.j])

14. Equation Solver:
Solve a set of linear equations using NumPy's linear algebra module. This illustrates the practical application of NumPy in solving mathematical problems.

In [81]:
arr1 = np.array([[2,4],[5,3]])
arr2 = np.array([8,13])
linear_equation = np.linalg.solve(arr1,arr2)
linear_equation

array([2., 1.])