<a href="https://colab.research.google.com/github/mukhi19113/Adyapan/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


1. The Clean Slate: Create a 1D array of numbers from 0 to 9, and then reverse it.

In [3]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

2. The Grid: Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. The Replacer: Create a 1D array of numbers from 1 to 10. Replace all odd numbers
with -1 without changing the original array.

In [9]:
a= np.arange(1,11)
a[a%2==1]= -1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


4. The Boundary: Create a 5x5 matrix with all 1s on the border and 0s on the inside

In [17]:
arr = np.ones((5,5)).astype(int)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


5. The Common Ground: Find the common elements between two NumPy arrays: a =
np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) and b = np.array([7, 2,
10, 2, 7, 4, 9, 4, 9, 8]).

In [18]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b= np.array([7,2,10,2,7,4,9,4,9,8])
common_elements = np.intersect1d(a,b)
common_elements

array([2, 4])

6. The Filter: Extract all numbers between 5 and 10 (inclusive) from this array: a =
np.array([2, 6, 1, 9, 10, 3, 27, 8, 4]).

In [25]:
a= np.array([2,6,1,9,10,3,27,8,4])
print(a[(a>5) & (a<=10)])

[ 6  9 10  8]


7. The Matchmaker: Given two arrays a and b of the same shape, get the positions
(indices) where elements of a and b match.

In [29]:
a= np.array([1,2,3,4,3,4])
b= np.array([4,5,2,6,7,4])
np.where(a==b)[0]


array([5])

8. The Normalizer: Create a random 5x5 matrix and normalize it (so that all values scale
between 0 and 1 using min-max normalization).

In [40]:
a= np.random.random((5,5))
normalized_array = (a-a.min())/(a.max()-a.min())
normalized_array

array([[0.16837974, 0.27174483, 0.86336315, 0.30329932, 0.24571575],
       [0.59432845, 0.70578879, 0.62937293, 0.1477273 , 0.34558666],
       [0.12604785, 0.92719038, 0.        , 0.00255474, 0.55991864],
       [0.71908773, 1.        , 0.47404781, 0.42986942, 0.89429712],
       [0.25794018, 0.07645195, 0.52460625, 0.42645375, 0.44376932]])

9. The Stack Overflow: Stack two arrays a = np.arange(10).reshape(2,5) and b
= np.repeat(1, 10).reshape(2,5) vertically.

In [49]:
a=np.arange(10).reshape(2,5)
b= np.repeat(1,10).reshape(2,5)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

10. The Peak Finder: Find the maximum value in each row of a 2D random 4x4 array, and
return both the values and their column indices.

In [56]:
a= np.random.random((4,4))
print(np.max(a,axis=1))
print(np.argmax(a,axis=1))



[0.59327409 0.80354437 0.74976942 0.62861526]
[0 0 0 2]
